/*
CREATION DE LA BASE 
*/
CREATE DATABASE IF NOT EXISTS PROJET_WEB;
USE PROJET_WEB;

/*CREATION DES TABLE*/
DROP TABLE IF EXISTS 'USER';
DROP TABLE IF EXISTS 'PRODUIT';
/*
TABLE USER (NOM,DATE_NAISSANCE,EMAIL,MOT_PASSE,ADRESSE...)
*/
CREATE TABLE IF NOT EXISTS USER(

)
/*
TABLE PRODUIT
*/
CREATE TABLE IF NOT EXISTS PRODUIT(

)
